name: Manual Test & Report Publish

on:
  workflow_dispatch:
    inputs:
      
      testng_file:
        description: 'TestNG Suite File'
        required: true
        default: 'testng.xml'  # Default testng file, can be overridden manually
        type: string

jobs:
  test-and-publish:
    runs-on: ubuntu-latest

    steps:
     

      # Set up Java (AdoptOpenJDK or any other distribution)
      - name: Set up Java
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'  # or 'zulu', 'adopt', etc.
          java-version: '17'  # Adjust as needed


      # Cache Maven dependencies to speed up builds
      - name: Cache Maven dependencies
        uses: actions/cache@v2
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      # Run Maven Tests and Generate the Report
      - name: Run Tests & Generate Report
        run: |
          mkdir -p reports
          echo "📦 Running TestNG Suite: ${{ github.event.inputs.testng_file }}"
          mvn clean test -DsuiteXmlFile=src/test/resources/${{ github.event.inputs.testng_file }}

      # Upload the generated report to GitHub Pages
      - name: Upload to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./reports
          destination_dir: ${{ github.event.inputs.branch }}-${{ github.run_number }}
          keep_files: true
